version: '2'

services:
  web:
    build: .
    image: fluence
    command: './bin/fluence'
    working_dir: /app/user
    environment:
    ports:
      - '3000:3000'
    depends_on:
    volumes:
      - '.:/app/user'

volumes:
  db:
